-- KDOG'S STAG — shared live database
-- Run this entire file in Supabase Dashboard > SQL Editor.

create table if not exists public.pub_suggestions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 28),
  created_at timestamptz not null default now()
);

create table if not exists public.employee_votes (
  id bigint generated by default as identity primary key,
  candidate text not null check (candidate in ('KDOG','THE INTERN','THE MANAGER','QUEER ASSISTANT','OTHER')),
  voter_id uuid not null unique,
  created_at timestamptz not null default now()
);

alter table public.pub_suggestions enable row level security;
alter table public.employee_votes enable row level security;

drop policy if exists "Anyone can read pub suggestions" on public.pub_suggestions;
drop policy if exists "Anyone can submit pub suggestions" on public.pub_suggestions;
drop policy if exists "Anyone can submit one vote per browser" on public.employee_votes;

create policy "Anyone can read pub suggestions"
on public.pub_suggestions for select
to anon, authenticated
using (true);

create policy "Anyone can submit pub suggestions"
on public.pub_suggestions for insert
to anon, authenticated
with check (char_length(trim(name)) between 1 and 28 and lower(trim(name)) <> 'wetherspoons');

create policy "Anyone can submit one vote per browser"
on public.employee_votes for insert
to anon, authenticated
with check (true);

-- Seed the same starter suggestions shown by the original demo.
insert into public.pub_suggestions (name)
select 'LANE 7' where not exists (select 1 from public.pub_suggestions where name='LANE 7');
insert into public.pub_suggestions (name)
select 'LANE 7' where (select count(*) from public.pub_suggestions where name='LANE 7') < 2;
insert into public.pub_suggestions (name)
select 'The pub' where not exists (select 1 from public.pub_suggestions where name='The pub');

-- Enable realtime for the word cloud table.
alter publication supabase_realtime add table public.pub_suggestions;
